version: "3"
services:
  app:
    build: .
    environment:
      DEBUG: "deck-workout:*"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/opt/app
      - reserved:/opt/app/node_modules/
    entrypoint:
      - npm
      - start

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: m0ng0!

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: m0ng0!

volumes:
  reserved:
